---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hive-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - hive.tunaos.org
  resources:
  - hivespokes
  - sharedauths
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.tunaos.org
  resources:
  - hivespokes/status
  - sharedauths/status
  verbs:
  - get
  - patch
  - update
