//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPin) DeepCopyInto(out *AgentPin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPin.
func (in *AgentPin) DeepCopy() *AgentPin {
	if in == nil {
		return nil
	}
	out := new(AgentPin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPlacementSnapshot) DeepCopyInto(out *AgentPlacementSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPlacementSnapshot.
func (in *AgentPlacementSnapshot) DeepCopy() *AgentPlacementSnapshot {
	if in == nil {
		return nil
	}
	out := new(AgentPlacementSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentState) DeepCopyInto(out *AgentState) {
	*out = *in
	if in.LastKick != nil {
		in, out := &in.LastKick, &out.LastKick
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentState.
func (in *AgentState) DeepCopy() *AgentState {
	if in == nil {
		return nil
	}
	out := new(AgentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentUsage) DeepCopyInto(out *AgentUsage) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentUsage.
func (in *AgentUsage) DeepCopy() *AgentUsage {
	if in == nil {
		return nil
	}
	out := new(AgentUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandSpec) DeepCopyInto(out *BandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandSpec.
func (in *BandSpec) DeepCopy() *BandSpec {
	if in == nil {
		return nil
	}
	out := new(BandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcleftRef) DeepCopyInto(out *CcleftRef) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcleftRef.
func (in *CcleftRef) DeepCopy() *CcleftRef {
	if in == nil {
		return nil
	}
	out := new(CcleftRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobRef) DeepCopyInto(out *CronJobRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobRef.
func (in *CronJobRef) DeepCopy() *CronJobRef {
	if in == nil {
		return nil
	}
	out := new(CronJobRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealRecord) DeepCopyInto(out *HealRecord) {
	*out = *in
	in.Last.DeepCopyInto(&out.Last)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealRecord.
func (in *HealRecord) DeepCopy() *HealRecord {
	if in == nil {
		return nil
	}
	out := new(HealRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHousekeeping) DeepCopyInto(out *HiveHousekeeping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHousekeeping.
func (in *HiveHousekeeping) DeepCopy() *HiveHousekeeping {
	if in == nil {
		return nil
	}
	out := new(HiveHousekeeping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveHousekeeping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHousekeepingList) DeepCopyInto(out *HiveHousekeepingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveHousekeeping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHousekeepingList.
func (in *HiveHousekeepingList) DeepCopy() *HiveHousekeepingList {
	if in == nil {
		return nil
	}
	out := new(HiveHousekeepingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveHousekeepingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHousekeepingSpec) DeepCopyInto(out *HiveHousekeepingSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]HousekeepingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Retire != nil {
		in, out := &in.Retire, &out.Retire
		*out = make([]RetiredCronJob, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHousekeepingSpec.
func (in *HiveHousekeepingSpec) DeepCopy() *HiveHousekeepingSpec {
	if in == nil {
		return nil
	}
	out := new(HiveHousekeepingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHousekeepingStatus) DeepCopyInto(out *HiveHousekeepingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]HousekeepingJobStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Retired != nil {
		in, out := &in.Retired, &out.Retired
		*out = make([]RetiredCronJobStatus, len(*in))
		copy(*out, *in)
	}
	if in.PendingActions != nil {
		in, out := &in.PendingActions, &out.PendingActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHousekeepingStatus.
func (in *HiveHousekeepingStatus) DeepCopy() *HiveHousekeepingStatus {
	if in == nil {
		return nil
	}
	out := new(HiveHousekeepingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveRelease) DeepCopyInto(out *HiveRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveRelease.
func (in *HiveRelease) DeepCopy() *HiveRelease {
	if in == nil {
		return nil
	}
	out := new(HiveRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveReleaseList) DeepCopyInto(out *HiveReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveReleaseList.
func (in *HiveReleaseList) DeepCopy() *HiveReleaseList {
	if in == nil {
		return nil
	}
	out := new(HiveReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveReleaseSpec) DeepCopyInto(out *HiveReleaseSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ReleaseTarget, len(*in))
		copy(*out, *in)
	}
	if in.Soak != nil {
		in, out := &in.Soak, &out.Soak
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(ReleaseWindow)
		**out = **in
	}
	if in.Blocklist != nil {
		in, out := &in.Blocklist, &out.Blocklist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveReleaseSpec.
func (in *HiveReleaseSpec) DeepCopy() *HiveReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(HiveReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveReleaseStatus) DeepCopyInto(out *HiveReleaseStatus) {
	*out = *in
	if in.Desired != nil {
		in, out := &in.Desired, &out.Desired
		*out = new(ResolvedImage)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = make(map[string]ResolvedImage, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ReleaseTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(RolloutProgress)
		(*in).DeepCopyInto(*out)
	}
	if in.Blocklist != nil {
		in, out := &in.Blocklist, &out.Blocklist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
	if in.LastRollbackAt != nil {
		in, out := &in.LastRollbackAt, &out.LastRollbackAt
		*out = (*in).DeepCopy()
	}
	if in.NextAttempt != nil {
		in, out := &in.NextAttempt, &out.NextAttempt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveReleaseStatus.
func (in *HiveReleaseStatus) DeepCopy() *HiveReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(HiveReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpoke) DeepCopyInto(out *HiveSpoke) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpoke.
func (in *HiveSpoke) DeepCopy() *HiveSpoke {
	if in == nil {
		return nil
	}
	out := new(HiveSpoke)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveSpoke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeList) DeepCopyInto(out *HiveSpokeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveSpoke, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeList.
func (in *HiveSpokeList) DeepCopy() *HiveSpokeList {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveSpokeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeSpec) DeepCopyInto(out *HiveSpokeSpec) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		**out = **in
	}
	if in.Pins != nil {
		in, out := &in.Pins, &out.Pins
		*out = make([]AgentPin, len(*in))
		copy(*out, *in)
	}
	if in.Holds != nil {
		in, out := &in.Holds, &out.Holds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentTiers != nil {
		in, out := &in.AgentTiers, &out.AgentTiers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(RotationPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pace != nil {
		in, out := &in.Pace, &out.Pace
		*out = new(PaceSpec)
		**out = **in
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(LivenessPolicySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeSpec.
func (in *HiveSpokeSpec) DeepCopy() *HiveSpokeSpec {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeStatus) DeepCopyInto(out *HiveSpokeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RotationPlan != nil {
		in, out := &in.RotationPlan, &out.RotationPlan
		*out = make([]RotationDecision, len(*in))
		copy(*out, *in)
	}
	if in.RotationPlanText != nil {
		in, out := &in.RotationPlanText, &out.RotationPlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Journal != nil {
		in, out := &in.Journal, &out.Journal
		*out = new(RotationJournal)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationAppliedAt != nil {
		in, out := &in.RotationAppliedAt, &out.RotationAppliedAt
		*out = (*in).DeepCopy()
	}
	if in.ContributorPlanText != nil {
		in, out := &in.ContributorPlanText, &out.ContributorPlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PacePlan != nil {
		in, out := &in.PacePlan, &out.PacePlan
		*out = make([]RotationDecision, len(*in))
		copy(*out, *in)
	}
	if in.PacePlanText != nil {
		in, out := &in.PacePlanText, &out.PacePlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PaceTickAt != nil {
		in, out := &in.PaceTickAt, &out.PaceTickAt
		*out = (*in).DeepCopy()
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(LivenessStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeStatus.
func (in *HiveSpokeStatus) DeepCopy() *HiveSpokeStatus {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HousekeepingJob) DeepCopyInto(out *HousekeepingJob) {
	*out = *in
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HousekeepingJob.
func (in *HousekeepingJob) DeepCopy() *HousekeepingJob {
	if in == nil {
		return nil
	}
	out := new(HousekeepingJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HousekeepingJobStatus) DeepCopyInto(out *HousekeepingJobStatus) {
	*out = *in
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HousekeepingJobStatus.
func (in *HousekeepingJobStatus) DeepCopy() *HousekeepingJobStatus {
	if in == nil {
		return nil
	}
	out := new(HousekeepingJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HousekeepingTemplate) DeepCopyInto(out *HousekeepingTemplate) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HousekeepingTemplate.
func (in *HousekeepingTemplate) DeepCopy() *HousekeepingTemplate {
	if in == nil {
		return nil
	}
	out := new(HousekeepingTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JournalPlacement) DeepCopyInto(out *JournalPlacement) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JournalPlacement.
func (in *JournalPlacement) DeepCopy() *JournalPlacement {
	if in == nil {
		return nil
	}
	out := new(JournalPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KiroBudgetStatus) DeepCopyInto(out *KiroBudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KiroBudgetStatus.
func (in *KiroBudgetStatus) DeepCopy() *KiroBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(KiroBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KiroEvictRequest) DeepCopyInto(out *KiroEvictRequest) {
	*out = *in
	in.Expiry.DeepCopyInto(&out.Expiry)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KiroEvictRequest.
func (in *KiroEvictRequest) DeepCopy() *KiroEvictRequest {
	if in == nil {
		return nil
	}
	out := new(KiroEvictRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivenessAction) DeepCopyInto(out *LivenessAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivenessAction.
func (in *LivenessAction) DeepCopy() *LivenessAction {
	if in == nil {
		return nil
	}
	out := new(LivenessAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivenessJournal) DeepCopyInto(out *LivenessJournal) {
	*out = *in
	if in.Heals != nil {
		in, out := &in.Heals, &out.Heals
		*out = make([]HealRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Panes != nil {
		in, out := &in.Panes, &out.Panes
		*out = make([]PaneRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resets != nil {
		in, out := &in.Resets, &out.Resets
		*out = make([]ProviderReset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HygieneAt != nil {
		in, out := &in.HygieneAt, &out.HygieneAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivenessJournal.
func (in *LivenessJournal) DeepCopy() *LivenessJournal {
	if in == nil {
		return nil
	}
	out := new(LivenessJournal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivenessPolicySpec) DeepCopyInto(out *LivenessPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivenessPolicySpec.
func (in *LivenessPolicySpec) DeepCopy() *LivenessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LivenessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivenessStatus) DeepCopyInto(out *LivenessStatus) {
	*out = *in
	if in.WatchdogAt != nil {
		in, out := &in.WatchdogAt, &out.WatchdogAt
		*out = (*in).DeepCopy()
	}
	if in.WatchdogPlan != nil {
		in, out := &in.WatchdogPlan, &out.WatchdogPlan
		*out = make([]LivenessAction, len(*in))
		copy(*out, *in)
	}
	if in.WatchdogPlanText != nil {
		in, out := &in.WatchdogPlanText, &out.WatchdogPlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NudgeAt != nil {
		in, out := &in.NudgeAt, &out.NudgeAt
		*out = (*in).DeepCopy()
	}
	if in.NudgePlan != nil {
		in, out := &in.NudgePlan, &out.NudgePlan
		*out = make([]LivenessAction, len(*in))
		copy(*out, *in)
	}
	if in.NudgePlanText != nil {
		in, out := &in.NudgePlanText, &out.NudgePlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Journal != nil {
		in, out := &in.Journal, &out.Journal
		*out = new(LivenessJournal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivenessStatus.
func (in *LivenessStatus) DeepCopy() *LivenessStatus {
	if in == nil {
		return nil
	}
	out := new(LivenessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadder) DeepCopyInto(out *ModelLadder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadder.
func (in *ModelLadder) DeepCopy() *ModelLadder {
	if in == nil {
		return nil
	}
	out := new(ModelLadder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLadder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderList) DeepCopyInto(out *ModelLadderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelLadder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderList.
func (in *ModelLadderList) DeepCopy() *ModelLadderList {
	if in == nil {
		return nil
	}
	out := new(ModelLadderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLadderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderSpec) DeepCopyInto(out *ModelLadderSpec) {
	*out = *in
	if in.BenchmarkSecretRef != nil {
		in, out := &in.BenchmarkSecretRef, &out.BenchmarkSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.InventoryConfigMapRef != nil {
		in, out := &in.InventoryConfigMapRef, &out.InventoryConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.Bands != nil {
		in, out := &in.Bands, &out.Bands
		*out = make([]BandSpec, len(*in))
		copy(*out, *in)
	}
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = make([]Rung, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderSpec.
func (in *ModelLadderSpec) DeepCopy() *ModelLadderSpec {
	if in == nil {
		return nil
	}
	out := new(ModelLadderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderStatus) DeepCopyInto(out *ModelLadderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Effective != nil {
		in, out := &in.Effective, &out.Effective
		*out = make([]Rung, len(*in))
		copy(*out, *in)
	}
	if in.Dropped != nil {
		in, out := &in.Dropped, &out.Dropped
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderStatus.
func (in *ModelLadderStatus) DeepCopy() *ModelLadderStatus {
	if in == nil {
		return nil
	}
	out := new(ModelLadderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaceSlotStatus) DeepCopyInto(out *PaceSlotStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaceSlotStatus.
func (in *PaceSlotStatus) DeepCopy() *PaceSlotStatus {
	if in == nil {
		return nil
	}
	out := new(PaceSlotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaceSpec) DeepCopyInto(out *PaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaceSpec.
func (in *PaceSpec) DeepCopy() *PaceSpec {
	if in == nil {
		return nil
	}
	out := new(PaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaneRecord) DeepCopyInto(out *PaneRecord) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaneRecord.
func (in *PaneRecord) DeepCopy() *PaneRecord {
	if in == nil {
		return nil
	}
	out := new(PaneRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolPaceSpec) DeepCopyInto(out *PoolPaceSpec) {
	*out = *in
	if in.SampleIntervalSeconds != nil {
		in, out := &in.SampleIntervalSeconds, &out.SampleIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolPaceSpec.
func (in *PoolPaceSpec) DeepCopy() *PoolPaceSpec {
	if in == nil {
		return nil
	}
	out := new(PoolPaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolPaceStatus) DeepCopyInto(out *PoolPaceStatus) {
	*out = *in
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = make([]PaceSlotStatus, len(*in))
		copy(*out, *in)
	}
	if in.KiroBudget != nil {
		in, out := &in.KiroBudget, &out.KiroBudget
		*out = new(KiroBudgetStatus)
		**out = **in
	}
	if in.LastActuation != nil {
		in, out := &in.LastActuation, &out.LastActuation
		*out = (*in).DeepCopy()
	}
	if in.ComputedAt != nil {
		in, out := &in.ComputedAt, &out.ComputedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolPaceStatus.
func (in *PoolPaceStatus) DeepCopy() *PoolPaceStatus {
	if in == nil {
		return nil
	}
	out := new(PoolPaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolRotationReading) DeepCopyInto(out *PoolRotationReading) {
	*out = *in
	if in.MeasuredAt != nil {
		in, out := &in.MeasuredAt, &out.MeasuredAt
		*out = (*in).DeepCopy()
	}
	if in.ComputedAt != nil {
		in, out := &in.ComputedAt, &out.ComputedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolRotationReading.
func (in *PoolRotationReading) DeepCopy() *PoolRotationReading {
	if in == nil {
		return nil
	}
	out := new(PoolRotationReading)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeConfigMapRef) DeepCopyInto(out *ProbeConfigMapRef) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeConfigMapRef.
func (in *ProbeConfigMapRef) DeepCopy() *ProbeConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ProbeConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccountStatus) DeepCopyInto(out *ProviderAccountStatus) {
	*out = *in
	if in.FetchedAt != nil {
		in, out := &in.FetchedAt, &out.FetchedAt
		*out = (*in).DeepCopy()
	}
	if in.RetryAt != nil {
		in, out := &in.RetryAt, &out.RetryAt
		*out = (*in).DeepCopy()
	}
	if in.Homes != nil {
		in, out := &in.Homes, &out.Homes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccountStatus.
func (in *ProviderAccountStatus) DeepCopy() *ProviderAccountStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCooldown) DeepCopyInto(out *ProviderCooldown) {
	*out = *in
	in.Until.DeepCopyInto(&out.Until)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCooldown.
func (in *ProviderCooldown) DeepCopy() *ProviderCooldown {
	if in == nil {
		return nil
	}
	out := new(ProviderCooldown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReset) DeepCopyInto(out *ProviderReset) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReset.
func (in *ProviderReset) DeepCopy() *ProviderReset {
	if in == nil {
		return nil
	}
	out := new(ProviderReset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderState) DeepCopyInto(out *ProviderState) {
	*out = *in
	if in.ResetsAt != nil {
		in, out := &in.ResetsAt, &out.ResetsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderState.
func (in *ProviderState) DeepCopy() *ProviderState {
	if in == nil {
		return nil
	}
	out := new(ProviderState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderWindowStatus) DeepCopyInto(out *ProviderWindowStatus) {
	*out = *in
	if in.ResetsAt != nil {
		in, out := &in.ResetsAt, &out.ResetsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderWindowStatus.
func (in *ProviderWindowStatus) DeepCopy() *ProviderWindowStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseTarget) DeepCopyInto(out *ReleaseTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseTarget.
func (in *ReleaseTarget) DeepCopy() *ReleaseTarget {
	if in == nil {
		return nil
	}
	out := new(ReleaseTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseTargetStatus) DeepCopyInto(out *ReleaseTargetStatus) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
	if in.PlacementsRestored != nil {
		in, out := &in.PlacementsRestored, &out.PlacementsRestored
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseTargetStatus.
func (in *ReleaseTargetStatus) DeepCopy() *ReleaseTargetStatus {
	if in == nil {
		return nil
	}
	out := new(ReleaseTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseWindow) DeepCopyInto(out *ReleaseWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseWindow.
func (in *ReleaseWindow) DeepCopy() *ReleaseWindow {
	if in == nil {
		return nil
	}
	out := new(ReleaseWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedImage) DeepCopyInto(out *ResolvedImage) {
	*out = *in
	if in.Platforms != nil {
		in, out := &in.Platforms, &out.Platforms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedImage.
func (in *ResolvedImage) DeepCopy() *ResolvedImage {
	if in == nil {
		return nil
	}
	out := new(ResolvedImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetiredCronJob) DeepCopyInto(out *RetiredCronJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetiredCronJob.
func (in *RetiredCronJob) DeepCopy() *RetiredCronJob {
	if in == nil {
		return nil
	}
	out := new(RetiredCronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetiredCronJobStatus) DeepCopyInto(out *RetiredCronJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetiredCronJobStatus.
func (in *RetiredCronJobStatus) DeepCopy() *RetiredCronJobStatus {
	if in == nil {
		return nil
	}
	out := new(RetiredCronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutProgress) DeepCopyInto(out *RolloutProgress) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.StepSince.DeepCopyInto(&out.StepSince)
	if in.PreviousAnnotations != nil {
		in, out := &in.PreviousAnnotations, &out.PreviousAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = make([]AgentPlacementSnapshot, len(*in))
		copy(*out, *in)
	}
	if in.Done != nil {
		in, out := &in.Done, &out.Done
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutProgress.
func (in *RolloutProgress) DeepCopy() *RolloutProgress {
	if in == nil {
		return nil
	}
	out := new(RolloutProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationDecision) DeepCopyInto(out *RotationDecision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationDecision.
func (in *RotationDecision) DeepCopy() *RotationDecision {
	if in == nil {
		return nil
	}
	out := new(RotationDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationJournal) DeepCopyInto(out *RotationJournal) {
	*out = *in
	if in.Stranded != nil {
		in, out := &in.Stranded, &out.Stranded
		*out = make([]JournalPlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PaceDemoted != nil {
		in, out := &in.PaceDemoted, &out.PaceDemoted
		*out = make([]JournalPlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KiroEvict != nil {
		in, out := &in.KiroEvict, &out.KiroEvict
		*out = make([]KiroEvictRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CanaryCooldown != nil {
		in, out := &in.CanaryCooldown, &out.CanaryCooldown
		*out = make([]ProviderCooldown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationJournal.
func (in *RotationJournal) DeepCopy() *RotationJournal {
	if in == nil {
		return nil
	}
	out := new(RotationJournal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicySpec) DeepCopyInto(out *RotationPolicySpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PeakProviders != nil {
		in, out := &in.PeakProviders, &out.PeakProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicySpec.
func (in *RotationPolicySpec) DeepCopy() *RotationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RotationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rung) DeepCopyInto(out *Rung) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rung.
func (in *Rung) DeepCopy() *Rung {
	if in == nil {
		return nil
	}
	out := new(Rung)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuth) DeepCopyInto(out *SharedAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuth.
func (in *SharedAuth) DeepCopy() *SharedAuth {
	if in == nil {
		return nil
	}
	out := new(SharedAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthList) DeepCopyInto(out *SharedAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SharedAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthList.
func (in *SharedAuthList) DeepCopy() *SharedAuthList {
	if in == nil {
		return nil
	}
	out := new(SharedAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthNamespaceStatus) DeepCopyInto(out *SharedAuthNamespaceStatus) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthNamespaceStatus.
func (in *SharedAuthNamespaceStatus) DeepCopy() *SharedAuthNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(SharedAuthNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthSpec) DeepCopyInto(out *SharedAuthSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dirs != nil {
		in, out := &in.Dirs, &out.Dirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Incumbent != nil {
		in, out := &in.Incumbent, &out.Incumbent
		*out = new(CronJobRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthSpec.
func (in *SharedAuthSpec) DeepCopy() *SharedAuthSpec {
	if in == nil {
		return nil
	}
	out := new(SharedAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthStatus) DeepCopyInto(out *SharedAuthStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]SharedAuthNamespaceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingRepairs != nil {
		in, out := &in.PendingRepairs, &out.PendingRepairs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthStatus.
func (in *SharedAuthStatus) DeepCopy() *SharedAuthStatus {
	if in == nil {
		return nil
	}
	out := new(SharedAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePool) DeepCopyInto(out *UsagePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePool.
func (in *UsagePool) DeepCopy() *UsagePool {
	if in == nil {
		return nil
	}
	out := new(UsagePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsagePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolList) DeepCopyInto(out *UsagePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UsagePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolList.
func (in *UsagePoolList) DeepCopy() *UsagePoolList {
	if in == nil {
		return nil
	}
	out := new(UsagePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsagePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolSpec) DeepCopyInto(out *UsagePoolSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]UsageWindowSpec, len(*in))
		copy(*out, *in)
	}
	if in.Reading != nil {
		in, out := &in.Reading, &out.Reading
		*out = new(ProbeConfigMapRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Ccleft != nil {
		in, out := &in.Ccleft, &out.Ccleft
		*out = new(CcleftRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Pace != nil {
		in, out := &in.Pace, &out.Pace
		*out = new(PoolPaceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolSpec.
func (in *UsagePoolSpec) DeepCopy() *UsagePoolSpec {
	if in == nil {
		return nil
	}
	out := new(UsagePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolStatus) DeepCopyInto(out *UsagePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]UsageWindowStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]UsageSourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(ProviderAccountStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationReading != nil {
		in, out := &in.RotationReading, &out.RotationReading
		*out = new(PoolRotationReading)
		(*in).DeepCopyInto(*out)
	}
	if in.PaceHistory != nil {
		in, out := &in.PaceHistory, &out.PaceHistory
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pace != nil {
		in, out := &in.Pace, &out.Pace
		*out = new(PoolPaceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolStatus.
func (in *UsagePoolStatus) DeepCopy() *UsagePoolStatus {
	if in == nil {
		return nil
	}
	out := new(UsagePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageSourceStatus) DeepCopyInto(out *UsageSourceStatus) {
	*out = *in
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = (*in).DeepCopy()
	}
	if in.UnpricedModels != nil {
		in, out := &in.UnpricedModels, &out.UnpricedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageSourceStatus.
func (in *UsageSourceStatus) DeepCopy() *UsageSourceStatus {
	if in == nil {
		return nil
	}
	out := new(UsageSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageWindowSpec) DeepCopyInto(out *UsageWindowSpec) {
	*out = *in
	out.Duration = in.Duration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageWindowSpec.
func (in *UsageWindowSpec) DeepCopy() *UsageWindowSpec {
	if in == nil {
		return nil
	}
	out := new(UsageWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageWindowStatus) DeepCopyInto(out *UsageWindowStatus) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = (*in).DeepCopy()
	}
	if in.ResetsAt != nil {
		in, out := &in.ResetsAt, &out.ResetsAt
		*out = (*in).DeepCopy()
	}
	if in.ExhaustionETA != nil {
		in, out := &in.ExhaustionETA, &out.ExhaustionETA
		*out = (*in).DeepCopy()
	}
	if in.ProviderWindow != nil {
		in, out := &in.ProviderWindow, &out.ProviderWindow
		*out = new(ProviderWindowStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageWindowStatus.
func (in *UsageWindowStatus) DeepCopy() *UsageWindowStatus {
	if in == nil {
		return nil
	}
	out := new(UsageWindowStatus)
	in.DeepCopyInto(out)
	return out
}
