//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPin) DeepCopyInto(out *AgentPin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPin.
func (in *AgentPin) DeepCopy() *AgentPin {
	if in == nil {
		return nil
	}
	out := new(AgentPin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentState) DeepCopyInto(out *AgentState) {
	*out = *in
	if in.LastKick != nil {
		in, out := &in.LastKick, &out.LastKick
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentState.
func (in *AgentState) DeepCopy() *AgentState {
	if in == nil {
		return nil
	}
	out := new(AgentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentUsage) DeepCopyInto(out *AgentUsage) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentUsage.
func (in *AgentUsage) DeepCopy() *AgentUsage {
	if in == nil {
		return nil
	}
	out := new(AgentUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandSpec) DeepCopyInto(out *BandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandSpec.
func (in *BandSpec) DeepCopy() *BandSpec {
	if in == nil {
		return nil
	}
	out := new(BandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpoke) DeepCopyInto(out *HiveSpoke) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpoke.
func (in *HiveSpoke) DeepCopy() *HiveSpoke {
	if in == nil {
		return nil
	}
	out := new(HiveSpoke)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveSpoke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeList) DeepCopyInto(out *HiveSpokeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveSpoke, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeList.
func (in *HiveSpokeList) DeepCopy() *HiveSpokeList {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveSpokeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeSpec) DeepCopyInto(out *HiveSpokeSpec) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		**out = **in
	}
	if in.Pins != nil {
		in, out := &in.Pins, &out.Pins
		*out = make([]AgentPin, len(*in))
		copy(*out, *in)
	}
	if in.Holds != nil {
		in, out := &in.Holds, &out.Holds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentTiers != nil {
		in, out := &in.AgentTiers, &out.AgentTiers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(RotationPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeSpec.
func (in *HiveSpokeSpec) DeepCopy() *HiveSpokeSpec {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveSpokeStatus) DeepCopyInto(out *HiveSpokeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RotationPlan != nil {
		in, out := &in.RotationPlan, &out.RotationPlan
		*out = make([]RotationDecision, len(*in))
		copy(*out, *in)
	}
	if in.RotationPlanText != nil {
		in, out := &in.RotationPlanText, &out.RotationPlanText
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveSpokeStatus.
func (in *HiveSpokeStatus) DeepCopy() *HiveSpokeStatus {
	if in == nil {
		return nil
	}
	out := new(HiveSpokeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadder) DeepCopyInto(out *ModelLadder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadder.
func (in *ModelLadder) DeepCopy() *ModelLadder {
	if in == nil {
		return nil
	}
	out := new(ModelLadder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLadder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderList) DeepCopyInto(out *ModelLadderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelLadder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderList.
func (in *ModelLadderList) DeepCopy() *ModelLadderList {
	if in == nil {
		return nil
	}
	out := new(ModelLadderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLadderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderSpec) DeepCopyInto(out *ModelLadderSpec) {
	*out = *in
	if in.BenchmarkSecretRef != nil {
		in, out := &in.BenchmarkSecretRef, &out.BenchmarkSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.InventoryConfigMapRef != nil {
		in, out := &in.InventoryConfigMapRef, &out.InventoryConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.Bands != nil {
		in, out := &in.Bands, &out.Bands
		*out = make([]BandSpec, len(*in))
		copy(*out, *in)
	}
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = make([]Rung, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderSpec.
func (in *ModelLadderSpec) DeepCopy() *ModelLadderSpec {
	if in == nil {
		return nil
	}
	out := new(ModelLadderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLadderStatus) DeepCopyInto(out *ModelLadderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Effective != nil {
		in, out := &in.Effective, &out.Effective
		*out = make([]Rung, len(*in))
		copy(*out, *in)
	}
	if in.Dropped != nil {
		in, out := &in.Dropped, &out.Dropped
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLadderStatus.
func (in *ModelLadderStatus) DeepCopy() *ModelLadderStatus {
	if in == nil {
		return nil
	}
	out := new(ModelLadderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeConfigMapRef) DeepCopyInto(out *ProbeConfigMapRef) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeConfigMapRef.
func (in *ProbeConfigMapRef) DeepCopy() *ProbeConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ProbeConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderState) DeepCopyInto(out *ProviderState) {
	*out = *in
	if in.ResetsAt != nil {
		in, out := &in.ResetsAt, &out.ResetsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderState.
func (in *ProviderState) DeepCopy() *ProviderState {
	if in == nil {
		return nil
	}
	out := new(ProviderState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationDecision) DeepCopyInto(out *RotationDecision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationDecision.
func (in *RotationDecision) DeepCopy() *RotationDecision {
	if in == nil {
		return nil
	}
	out := new(RotationDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicySpec) DeepCopyInto(out *RotationPolicySpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PeakProviders != nil {
		in, out := &in.PeakProviders, &out.PeakProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicySpec.
func (in *RotationPolicySpec) DeepCopy() *RotationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RotationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rung) DeepCopyInto(out *Rung) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rung.
func (in *Rung) DeepCopy() *Rung {
	if in == nil {
		return nil
	}
	out := new(Rung)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuth) DeepCopyInto(out *SharedAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuth.
func (in *SharedAuth) DeepCopy() *SharedAuth {
	if in == nil {
		return nil
	}
	out := new(SharedAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthList) DeepCopyInto(out *SharedAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SharedAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthList.
func (in *SharedAuthList) DeepCopy() *SharedAuthList {
	if in == nil {
		return nil
	}
	out := new(SharedAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthNamespaceStatus) DeepCopyInto(out *SharedAuthNamespaceStatus) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthNamespaceStatus.
func (in *SharedAuthNamespaceStatus) DeepCopy() *SharedAuthNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(SharedAuthNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthSpec) DeepCopyInto(out *SharedAuthSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dirs != nil {
		in, out := &in.Dirs, &out.Dirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthSpec.
func (in *SharedAuthSpec) DeepCopy() *SharedAuthSpec {
	if in == nil {
		return nil
	}
	out := new(SharedAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAuthStatus) DeepCopyInto(out *SharedAuthStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]SharedAuthNamespaceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingRepairs != nil {
		in, out := &in.PendingRepairs, &out.PendingRepairs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAuthStatus.
func (in *SharedAuthStatus) DeepCopy() *SharedAuthStatus {
	if in == nil {
		return nil
	}
	out := new(SharedAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePool) DeepCopyInto(out *UsagePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePool.
func (in *UsagePool) DeepCopy() *UsagePool {
	if in == nil {
		return nil
	}
	out := new(UsagePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsagePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolList) DeepCopyInto(out *UsagePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UsagePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolList.
func (in *UsagePoolList) DeepCopy() *UsagePoolList {
	if in == nil {
		return nil
	}
	out := new(UsagePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsagePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolSpec) DeepCopyInto(out *UsagePoolSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]UsageWindowSpec, len(*in))
		copy(*out, *in)
	}
	if in.Reading != nil {
		in, out := &in.Reading, &out.Reading
		*out = new(ProbeConfigMapRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolSpec.
func (in *UsagePoolSpec) DeepCopy() *UsagePoolSpec {
	if in == nil {
		return nil
	}
	out := new(UsagePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePoolStatus) DeepCopyInto(out *UsagePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]UsageWindowStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]UsageSourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePoolStatus.
func (in *UsagePoolStatus) DeepCopy() *UsagePoolStatus {
	if in == nil {
		return nil
	}
	out := new(UsagePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageSourceStatus) DeepCopyInto(out *UsageSourceStatus) {
	*out = *in
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = (*in).DeepCopy()
	}
	if in.UnpricedModels != nil {
		in, out := &in.UnpricedModels, &out.UnpricedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageSourceStatus.
func (in *UsageSourceStatus) DeepCopy() *UsageSourceStatus {
	if in == nil {
		return nil
	}
	out := new(UsageSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageWindowSpec) DeepCopyInto(out *UsageWindowSpec) {
	*out = *in
	out.Duration = in.Duration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageWindowSpec.
func (in *UsageWindowSpec) DeepCopy() *UsageWindowSpec {
	if in == nil {
		return nil
	}
	out := new(UsageWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageWindowStatus) DeepCopyInto(out *UsageWindowStatus) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = (*in).DeepCopy()
	}
	if in.ResetsAt != nil {
		in, out := &in.ResetsAt, &out.ResetsAt
		*out = (*in).DeepCopy()
	}
	if in.ExhaustionETA != nil {
		in, out := &in.ExhaustionETA, &out.ExhaustionETA
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageWindowStatus.
func (in *UsageWindowStatus) DeepCopy() *UsageWindowStatus {
	if in == nil {
		return nil
	}
	out := new(UsageWindowStatus)
	in.DeepCopyInto(out)
	return out
}
